export const USER_CREATE_PROJECT = "USER_CREATE_PROJECT";
export const USER_DELETE_PROJECT = "USER_DELETE_PROJECT";
export const USER_EDIT_PROJECT = "USER_EDIT_PROJECT";
export const USER_LOGOUT = "USER_LOGOUT";
